/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Class.Koneksi;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class Penjualan_Order extends javax.swing.JFrame {

    /**
     * Creates new form Penjualan_penjualanFIT
     */
    boolean pencarian_tgl = false;

    public Penjualan_Order() {
        initComponents();
        this.setLocationRelativeTo(null);
        loadData();
    }

    void loadData() {
        try {
            DefaultTableModel model = (DefaultTableModel) tbl_order.getModel();
            model.setRowCount(0);
            String sql = "SELECT o.tgl_order, o.no_faktur_order, s.nama_salesman, c.nama_customer, c.alamat_customer, o.status_revisi from `order` o join salesman s on s.kode_salesman = o.kode_pegawai join customer c on c.kode_customer = o.kode_customer order by o.tgl_order desc";
            java.sql.Connection conn = (Connection) Koneksi.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            int baris = 0;
            while (res.next()) {
                model.addRow(new Object[]{"", "", "", "", "", "", ""});
                String tanggal = res.getString("tgl_order");
                String no_faktur_order = res.getString("no_faktur_order");
                String nama_pegawai = res.getString("nama_salesman");
                String nama_customer = res.getString("nama_customer");
                String alamat_customer = res.getString("alamat_customer");
                String status_revisi = res.getString("status_revisi");
                if (status_revisi.equals("0")) {
                    status_revisi = "DITOLAK";
                } else {
                    status_revisi = "DITERIMA";
                }
                model.setValueAt(tanggal, baris, 0);
                model.setValueAt(no_faktur_order, baris, 1);
                model.setValueAt(nama_pegawai, baris, 2);
                model.setValueAt(nama_customer, baris, 3);
                model.setValueAt(alamat_customer, baris, 4);
                model.setValueAt(status_revisi, baris, 5);
                baris++;
            }
            conn.close();
            res.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Eror" + e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel14 = new javax.swing.JLabel();
        txt_kriteria = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane7 = new javax.swing.JScrollPane();
        tbl_order = new javax.swing.JTable();
        cek_tgl = new javax.swing.JCheckBox();
        jLabel17 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel18 = new javax.swing.JLabel();
        com_filter = new javax.swing.JComboBox<>();
        tgl_awal = new com.toedter.calendar.JDateChooser();
        tgl_akhir = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("Kriteria");

        txt_kriteria.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.gray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        txt_kriteria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_kriteriaMouseClicked(evt);
            }
        });
        txt_kriteria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_kriteriaKeyPressed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/cancel (3).png"))); // NOI18N
        jLabel15.setText("Delete");
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.lightGray));

        jLabel16.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel16.setText("DAFTAR ORDER ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(326, 326, 326)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel16)
                .addGap(5, 5, 5))
        );

        jSeparator2.setForeground(new java.awt.Color(153, 153, 153));

        tbl_order.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Tanggal", "No. Order", "Salesman", "Customer", "Alamat", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_order.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_orderMouseClicked(evt);
            }
        });
        tbl_order.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tbl_orderKeyPressed(evt);
            }
        });
        jScrollPane7.setViewportView(tbl_order);

        cek_tgl.setText("Tanggal");
        cek_tgl.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cek_tglItemStateChanged(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setText("s.d.");

        jSeparator3.setForeground(new java.awt.Color(153, 153, 153));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator4.setForeground(new java.awt.Color(153, 153, 153));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel18.setText("Filter");

        com_filter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SEMUA", "DITERIMA", "DITOLAK", "BELUM DIKONFIRMASI" }));
        com_filter.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                com_filterItemStateChanged(evt);
            }
        });
        com_filter.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                com_filterVetoableChange(evt);
            }
        });

        tgl_awal.setDateFormatString(" yyyy- MM-dd");
        tgl_awal.setEnabled(false);
        tgl_awal.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tgl_awalPropertyChange(evt);
            }
        });
        tgl_awal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tgl_awalKeyPressed(evt);
            }
        });

        tgl_akhir.setDateFormatString(" yyyy- MM-dd");
        tgl_akhir.setEnabled(false);
        tgl_akhir.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tgl_akhirPropertyChange(evt);
            }
        });
        tgl_akhir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tgl_akhirKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane7)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 864, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cek_tgl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tgl_awal, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel17)
                        .addGap(2, 2, 2)
                        .addComponent(tgl_akhir, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(com_filter, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_kriteria, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(txt_kriteria, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel15)))
                .addGap(2, 2, 2)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cek_tgl)
                        .addComponent(jLabel17)
                        .addComponent(jLabel18)
                        .addComponent(com_filter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tgl_awal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tgl_akhir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_kriteriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_kriteriaMouseClicked

    }//GEN-LAST:event_txt_kriteriaMouseClicked


    private void tbl_orderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_orderMouseClicked

        if (evt.getClickCount() == 2) {
            try {
                Penjualan_Order_DetailOrder podo = new Penjualan_Order_DetailOrder(tbl_order.getValueAt(tbl_order.getSelectedRow(), 1).toString(), this);
                podo.setVisible(true);
                podo.setFocusable(true);
            } catch (NullPointerException e) {
                JOptionPane.showMessageDialog(null, "Pilih data yang ada");
            }

        }
    }//GEN-LAST:event_tbl_orderMouseClicked

    private void tgl_awalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tgl_awalKeyPressed

    }//GEN-LAST:event_tgl_awalKeyPressed

    private void tgl_akhirKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tgl_akhirKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tgl_akhirKeyPressed

    private void txt_kriteriaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_kriteriaKeyPressed
        txt_kriteria.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                loadDataKriteria();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                loadDataKriteria();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                //loadDataKriteria();
            }

        });
    }//GEN-LAST:event_txt_kriteriaKeyPressed

    private void tgl_akhirPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tgl_akhirPropertyChange
        loadDataKriteria();
    }//GEN-LAST:event_tgl_akhirPropertyChange

    private void tgl_awalPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tgl_awalPropertyChange
        loadDataKriteria();
    }//GEN-LAST:event_tgl_awalPropertyChange

    private void com_filterVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_com_filterVetoableChange

    }//GEN-LAST:event_com_filterVetoableChange

    private void com_filterItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_com_filterItemStateChanged
        loadDataKriteria();
        System.out.println("filfil");
    }//GEN-LAST:event_com_filterItemStateChanged

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        hapus_tabel();
    }//GEN-LAST:event_jLabel15MouseClicked

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_DELETE) {
            hapus_tabel();
        }
        if (evt.getKeyCode() == KeyEvent.VK_F5) {
            hapus_tabel();
        }
    }//GEN-LAST:event_formKeyPressed

    private void tbl_orderKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbl_orderKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_DELETE) {
            hapus_tabel();
        }
        if (evt.getKeyCode() == KeyEvent.VK_F5) {
            hapus_tabel();
        }
    }//GEN-LAST:event_tbl_orderKeyPressed

    private void cek_tglItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cek_tglItemStateChanged
        if (cek_tgl.isSelected()) {
            tgl_awal.setEnabled(true);
            tgl_akhir.setEnabled(true);
            pencarian_tgl = true;
        } else {
            tgl_awal.setEnabled(false);
            tgl_akhir.setEnabled(false);
            pencarian_tgl = false;            
        }loadDataKriteria();
    }//GEN-LAST:event_cek_tglItemStateChanged
    void hapus_tabel() {
        if (tbl_order.getRowCount() - 1 == -1) {
            JOptionPane.showMessageDialog(null, "Data didalam tabel telah tiada.", "", 2);
        } else {
            removeSelectedRows(tbl_order);
        }
    }

    private void removeSelectedRows(JTable table) {
        int Hapus = 1;
        try {
            Koneksi Koneksi = new Koneksi();
            Connection con = Koneksi.configDB();
            Statement st = con.createStatement();
            int row = 0;
            Hapus = JOptionPane.showConfirmDialog(null, "Apakah anda yakin mau menghapus baris ?", "konfirmasi", JOptionPane.YES_NO_OPTION);
            if (Hapus == 0) {
                DefaultTableModel model = (DefaultTableModel) this.tbl_order.getModel();
                int[] rows = table.getSelectedRows();
                for (int i = 0; i < rows.length; i++) {
                    System.out.println("row ke-i adalah " + rows[i]);
                    if (rows[i] == 0 || rows.length == 1) {
                        String no_faktur_order = String.valueOf(model.getValueAt(rows[i], 1));
                        //update_stok(no_bukti);
                        String sql = "delete from `order` where no_faktur_order='" + no_faktur_order + "'";
                        System.out.println(sql);
                        String sql2 = "delete from order_detail where no_faktur_order='" + no_faktur_order + "'";
                        row = st.executeUpdate(sql);
                        row = st.executeUpdate(sql2);
                        System.out.println("if" + (rows[i]));
                        model.removeRow(rows[i]);
                    } else {
                        System.out.println("if 2");
                        if (i == 0) {
                            String no_faktur_order = String.valueOf(model.getValueAt(rows[i], 1));
                            //update_stok(no_bukti);
                            String sql = "delete from `order` where no_faktur_order='" + no_faktur_order + "'";
                            System.out.println(sql);
                            String sql2 = "delete from order_detail where no_faktur_order='" + no_faktur_order + "'";
                            row = st.executeUpdate(sql);
                            row = st.executeUpdate(sql2);
                            model.removeRow(rows[i]);
                        } else {
                            String no_faktur_order = String.valueOf(model.getValueAt(rows[i], 1));
                            //update_stok(no_bukti);
                            String sql = "delete from `order` where no_faktur_order='" + no_faktur_order + "'";
                            System.out.println(sql);
                            String sql2 = "delete from order_detail where no_faktur_order='" + no_faktur_order + "'";
                            row = st.executeUpdate(sql);
                            row = st.executeUpdate(sql2);
                            model.removeRow(rows[i] - i);
                        }
                    }

                }

            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "data tidak dimasukkan ke database" + e, "informasi", JOptionPane.INFORMATION_MESSAGE);
        }

    }

    void loadDataKriteria() {
        try {
            String status = com_filter.getSelectedItem().toString();
            if (status.equals("SEMUA")) {
                status = "'1' OR status_revisi='0'";
            } else if (status.equals("DITOLAK")) {
                status = "'0'";
            } else if (status.equals("DITERIMA")) {
                status = "'1'";
            } else {
                status = "'1' OR status_revisi='0'";
            }
            DefaultTableModel model = (DefaultTableModel) tbl_order.getModel();
            model.setRowCount(0);
            String sql = "";
            if (pencarian_tgl || cek_tgl.isSelected()) {
                String awal = "", akhir = "";
                if (tgl_awal.getDate() != null && tgl_akhir.getDate() != null) {
                    SimpleDateFormat ft_awal = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
                    awal = ft_awal.format(tgl_awal.getDate());
                    SimpleDateFormat ft_akhir = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
                    akhir = ft_akhir.format(tgl_akhir.getDate());
                }
                sql = "SELECT o.tgl_order, o.no_faktur_order, s.nama_salesman, c.nama_customer, c.alamat_customer, o.status_revisi from `order` o join salesman s on s.kode_salesman = o.kode_pegawai join customer c on c.kode_customer = o.kode_customer where (c.nama_customer like '%" + txt_kriteria.getText() + "%' OR s.nama_salesman like '%" + txt_kriteria.getText() + "%' OR o.no_faktur_order like '%" + txt_kriteria.getText() + "%') and o.tgl_order between '" + awal + "' and '" + akhir + "' and o.status_revisi =" + status + " order by o.tgl_order desc";
            } else {
                sql = "SELECT o.tgl_order, o.no_faktur_order, s.nama_salesman, c.nama_customer, c.alamat_customer, o.status_revisi from `order` o join salesman s on s.kode_salesman = o.kode_pegawai join customer c on c.kode_customer = o.kode_customer where (c.nama_customer like '%" + txt_kriteria.getText() + "%' OR s.nama_salesman like '%" + txt_kriteria.getText() + "%' OR o.no_faktur_order like '%" + txt_kriteria.getText() + "%') and o.status_revisi=" + status + " order by o.tgl_order desc";
            }
            System.out.println(sql);
            java.sql.Connection conn = (Connection) Koneksi.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            int baris = 0;
            while (res.next()) {
                model.addRow(new Object[]{"", "", "", "", "", "", ""});
                String tanggal = res.getString("tgl_order");
                String no_faktur_order = res.getString("no_faktur_order");
                String nama_pegawai = res.getString("nama_salesman");
                String nama_customer = res.getString("nama_customer");
                String alamat_customer = res.getString("alamat_customer");
                String status_revisi = res.getString("status_revisi");
                if (status_revisi.equals("0")) {
                    status_revisi = "DITOLAK";
                } else {
                    status_revisi = "DITERIMA";
                }

                model.setValueAt(tanggal, baris, 0);
                model.setValueAt(no_faktur_order, baris, 1);
                model.setValueAt(nama_pegawai, baris, 2);
                model.setValueAt(nama_customer, baris, 3);
                model.setValueAt(alamat_customer, baris, 4);
                model.setValueAt(status_revisi, baris, 5);
                baris++;
            }
            conn.close();
            res.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Eror" + e);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Penjualan_HasilRevisiPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Penjualan_HasilRevisiPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Penjualan_HasilRevisiPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Penjualan_HasilRevisiPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Penjualan_Order().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cek_tgl;
    private javax.swing.JComboBox<String> com_filter;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTable tbl_order;
    private com.toedter.calendar.JDateChooser tgl_akhir;
    private com.toedter.calendar.JDateChooser tgl_awal;
    private javax.swing.JTextField txt_kriteria;
    // End of variables declaration//GEN-END:variables
}
