/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Class.Koneksi;
import Java.Connect;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author USER
 */
public class Penjualan_RevisiPenjualan extends javax.swing.JFrame {
    private Connect connection;
    /**
     * Creates new form Penjualan_RevisiPenjualan
     */
    private DefaultTableModel model;
    public Penjualan_RevisiPenjualan() {
        initComponents();
        this.setLocationRelativeTo(null);
        loadNumberTable();
        loadData();
//        AturlebarKolom();
//        loadTanggal();
    }
    
    public Penjualan_RevisiPenjualan(Connect connection) {
        initComponents();
        this.setLocationRelativeTo(null);
        loadNumberTable();
//        AturlebarKolom();
//        loadTanggal();
        loadData();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel14 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_revisi = new javax.swing.JTable();

        setDefaultCloseOperation(DISPOSE_ON_CLOSE);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("Kriteria");

        jTextField5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.gray, java.awt.Color.lightGray, java.awt.Color.lightGray));

        jSeparator2.setForeground(new java.awt.Color(153, 153, 153));

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.lightGray));

        jLabel16.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel16.setText("REVISI PENJUALAN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(367, 367, 367)
                .addComponent(jLabel16)
                .addContainerGap(359, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(jLabel16)
                .addGap(3, 3, 3))
        );

        jScrollPane2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.white));

        tbl_revisi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No", "No Faktur", "Tanggal", "T.O.P", "Salesman", "Kota", "Customer", "Total Nota"
            }
        ));
        tbl_revisi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_revisiMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_revisi);
        if (tbl_revisi.getColumnModel().getColumnCount() > 0) {
            tbl_revisi.getColumnModel().getColumn(0).setPreferredWidth(10);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_kritMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_kritMouseClicked
        //       Penjualan_Penjualan_Pilihcustomer pppc = new Penjualan_Penjualan_Pilihcustomer();
        //       pppc.setVisible(true);
        //       pppc.setFocusable(true);
    }//GEN-LAST:event_tbl_kritMouseClicked
 void pop_up() {
        Penjualan_RevisiPenjualan_Faktur magdn = new Penjualan_RevisiPenjualan_Faktur(connection);
        magdn.setVisible(true);
        magdn.setFocusable(true);
    }
    private void tbl_revisiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_revisiMouseClicked
       if (evt.getClickCount() == 1) {
            try {
                Penjualan_RevisiPenjualan_Faktur magdn = new Penjualan_RevisiPenjualan_Faktur(tbl_revisi.getValueAt(tbl_revisi.getSelectedRow(), 1).toString(), true);
                magdn.setVisible(true);
                magdn.setFocusable(true);
            } catch (NullPointerException e) {
                JOptionPane.showMessageDialog(null, "Pilih data yang ada");
            }

        }
    }//GEN-LAST:event_tbl_revisiMouseClicked

    private void tbl_kritKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbl_kritKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tbl_kritKeyReleased

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Penjualan_RevisiPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Penjualan_RevisiPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Penjualan_RevisiPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Penjualan_RevisiPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Penjualan_RevisiPenjualan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTable tbl_revisi;
    // End of variables declaration//GEN-END:variables

    private void loadNumberTable() {
        int baris = tbl_revisi.getRowCount();
        for (int a = 0; a < baris; a++) {
            String nomor = String.valueOf(a + 1);
            tbl_revisi.setValueAt(nomor + ".", a, 0);
        }
    }
    
    public void loadData() {
        try {
            DefaultTableModel model = (DefaultTableModel) tbl_revisi.getModel();
            model.setRowCount(0);
            String sql = "SELECT penjualan.tgl_penjualan, p.no_faktur_order, top.nama_top, "
                + "salesman.nama_salesman,customer.kota_customer, customer.nama_customer"
                + " from `order` AS p INNER JOIN penjualan ON "
                + "penjualan.no_faktur_order = p.no_faktur_order LEFT OUTER JOIN "
                + "top ON p.id_top = top.id_top LEFT OUTER JOIN salesman ON "
                + "penjualan.kode_salesman = salesman.kode_salesman LEFT OUTER JOIN "
                + "customer ON p.kode_customer = customer.kode_customer order by p.tgl_order ASC";
            System.out.println(sql);
            java.sql.Connection conn = (Connection) Koneksi.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            int baris = 0;
            while (res.next()) {
                model.addRow(new Object[]{"","", "", "", "", "", ""});
                loadNumberTable();
                String no_faktur_order = res.getString("no_faktur_order");
                String tgl_penjualan = res.getString("tgl_penjualan");
                String nama_top = res.getString("nama_top");
                String nama_salesman = res.getString("nama_salesman");
                String kota_customer = res.getString("kota_customer");
                String nama_customer = res.getString("nama_customer");
                TableColumn column = tbl_revisi.getColumnModel().getColumn(1);column.setMinWidth(0);column.setMaxWidth(0);column.setWidth(0);column.setPreferredWidth(0);
                model.setValueAt(no_faktur_order, baris, 1);
                model.setValueAt(tgl_penjualan, baris, 2);
                model.setValueAt(nama_top, baris, 3);
                model.setValueAt(nama_salesman, baris, 4);
                model.setValueAt(kota_customer, baris, 5);
                model.setValueAt(nama_customer, baris, 6);
                baris++;
            }
            conn.close();
            res.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Eror" + e);
        }
    }
    void AturlebarKolom() {
        TableColumn column;
        tbl_revisi.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        column = tbl_revisi.getColumnModel().getColumn(0);
        column.setMinWidth(0);
        column.setMaxWidth(0);
        column = tbl_revisi.getColumnModel().getColumn(1);
        column.setPreferredWidth(50);
        column = tbl_revisi.getColumnModel().getColumn(2);
        column.setPreferredWidth(200);
        column = tbl_revisi.getColumnModel().getColumn(3);
        column.setPreferredWidth(70);
        column = tbl_revisi.getColumnModel().getColumn(4);
        column.setPreferredWidth(60);
        column = tbl_revisi.getColumnModel().getColumn(5);
        column.setPreferredWidth(50);
        column = tbl_revisi.getColumnModel().getColumn(6);
        column.setPreferredWidth(90);
       
      

    }
}




// private void loadTanggal() {
//        
//        Object header[] = {"TANGGAL", "T.O.P", "SALESMAN", "KOTA", "CUSTOMER","TOTAL NOTA"};
//        DefaultTableModel data = new DefaultTableModel(null, header);
//        tbl_revisi.setModel(data);
//
//        String sql = "SELECT penjualan.tgl_penjualan, p.no_faktur_order, top.nama_top, "
//                + "salesman.nama_salesman,customer.kota_customer, customer.nama_customer"
//                + " from `order` AS p INNER JOIN penjualan ON "
//                + "penjualan.no_faktur_order = p.no_faktur_order LEFT OUTER JOIN "
//                + "top ON p.id_top = top.id_top LEFT OUTER JOIN salesman ON "
//                + "penjualan.kode_salesman = salesman.kode_salesman LEFT OUTER JOIN "
//                + "customer ON p.kode_customer = customer.kode_customer order by p.no_faktur_order ASC";
//        try {
//            java.sql.Connection conn = (Connection) Koneksi.configDB();
//            java.sql.Statement stm = conn.createStatement();
//            java.sql.ResultSet res = stm.executeQuery(sql);
//            while (res.next()) {
//                String kolom1 = res.getString(1);
//                String kolom2 = res.getString(3);
//                String kolom3 = res.getString(4);
//                String kolom4 = res.getString(5);
//                String kolom5 = res.getString(6);
//                String kolom[] = {kolom1, kolom2, kolom3, kolom4, kolom5};
//                data.addRow(kolom);
//            }
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(null, "error :" + e.getMessage());
//        }
//    }
//}
